/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ColumnService } from "../column.service";
import { ColumnCreateInput } from "./ColumnCreateInput";
import { Column } from "./Column";
import { ColumnFindManyArgs } from "./ColumnFindManyArgs";
import { ColumnWhereUniqueInput } from "./ColumnWhereUniqueInput";
import { ColumnUpdateInput } from "./ColumnUpdateInput";
import { CardFindManyArgs } from "../../card/base/CardFindManyArgs";
import { Card } from "../../card/base/Card";
import { CardWhereUniqueInput } from "../../card/base/CardWhereUniqueInput";

export class ColumnControllerBase {
  constructor(protected readonly service: ColumnService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Column })
  async createColumn(@common.Body() data: ColumnCreateInput): Promise<Column> {
    return await this.service.createColumn({
      data: {
        ...data,

        board: data.board
          ? {
              connect: data.board,
            }
          : undefined,
      },
      select: {
        board: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Column] })
  @ApiNestedQuery(ColumnFindManyArgs)
  async columns(@common.Req() request: Request): Promise<Column[]> {
    const args = plainToClass(ColumnFindManyArgs, request.query);
    return this.service.columns({
      ...args,
      select: {
        board: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Column })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async column(
    @common.Param() params: ColumnWhereUniqueInput
  ): Promise<Column | null> {
    const result = await this.service.column({
      where: params,
      select: {
        board: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Column })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateColumn(
    @common.Param() params: ColumnWhereUniqueInput,
    @common.Body() data: ColumnUpdateInput
  ): Promise<Column | null> {
    try {
      return await this.service.updateColumn({
        where: params,
        data: {
          ...data,

          board: data.board
            ? {
                connect: data.board,
              }
            : undefined,
        },
        select: {
          board: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Column })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteColumn(
    @common.Param() params: ColumnWhereUniqueInput
  ): Promise<Column | null> {
    try {
      return await this.service.deleteColumn({
        where: params,
        select: {
          board: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/cards")
  @ApiNestedQuery(CardFindManyArgs)
  async findCards(
    @common.Req() request: Request,
    @common.Param() params: ColumnWhereUniqueInput
  ): Promise<Card[]> {
    const query = plainToClass(CardFindManyArgs, request.query);
    const results = await this.service.findCards(params.id, {
      ...query,
      select: {
        board: {
          select: {
            id: true,
          },
        },

        column: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cards")
  async connectCards(
    @common.Param() params: ColumnWhereUniqueInput,
    @common.Body() body: CardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cards: {
        connect: body,
      },
    };
    await this.service.updateColumn({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cards")
  async updateCards(
    @common.Param() params: ColumnWhereUniqueInput,
    @common.Body() body: CardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cards: {
        set: body,
      },
    };
    await this.service.updateColumn({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cards")
  async disconnectCards(
    @common.Param() params: ColumnWhereUniqueInput,
    @common.Body() body: CardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cards: {
        disconnect: body,
      },
    };
    await this.service.updateColumn({
      where: params,
      data,
      select: { id: true },
    });
  }
}
